package korail;

import java.io.Serializable;

/**
 * 공지사항 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AnnounceErm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/**
	 * 생성자.
	 */
	public AnnounceErm() {
	}


}
