package korail;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 예매 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BookingErm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 예약번호. */
	private  bookingNm;

	/** 기차. */
	private TrainErm train;

	/** 티켓 수량. */
	private  bookingQty;

	/** 좌석 에매. */
	private  bookingSit;

	/** 승차권 나이별. */
	private  bookingAge;

	/** 티켓 가격. */
	private  bookingPrice;

	/** 기차역. */
	private StationErm station;

	/** 고객 목록. */
	private Set<UserErm> userSet;

	/**
	 * 생성자.
	 */
	public BookingErm() {
		this.userSet = new HashSet<UserErm>();
	}

	/**
	 * 예약번호을 설정합니다..
	 * 
	 * @param bookingNm
	 *            예약번호
	 */
	public void setBookingNm( bookingNm) {
		this.bookingNm = bookingNm;
	}

	/**
	 * 예약번호을 가져옵니다..
	 * 
	 * @return 예약번호
	 */
	public  getBookingNm() {
		return this.bookingNm;
	}

	/**
	 * 기차을 설정합니다..
	 * 
	 * @param train
	 *            기차
	 */
	public void setTrain(TrainErm train) {
		this.train = train;
	}

	/**
	 * 기차을 가져옵니다..
	 * 
	 * @return 기차
	 */
	public TrainErm getTrain() {
		return this.train;
	}

	/**
	 * 티켓 수량을 설정합니다..
	 * 
	 * @param bookingQty
	 *            티켓 수량
	 */
	public void setBookingQty( bookingQty) {
		this.bookingQty = bookingQty;
	}

	/**
	 * 티켓 수량을 가져옵니다..
	 * 
	 * @return 티켓 수량
	 */
	public  getBookingQty() {
		return this.bookingQty;
	}

	/**
	 * 좌석 에매을 설정합니다..
	 * 
	 * @param bookingSit
	 *            좌석 에매
	 */
	public void setBookingSit( bookingSit) {
		this.bookingSit = bookingSit;
	}

	/**
	 * 좌석 에매을 가져옵니다..
	 * 
	 * @return 좌석 에매
	 */
	public  getBookingSit() {
		return this.bookingSit;
	}

	/**
	 * 승차권 나이별을 설정합니다..
	 * 
	 * @param bookingAge
	 *            승차권 나이별
	 */
	public void setBookingAge( bookingAge) {
		this.bookingAge = bookingAge;
	}

	/**
	 * 승차권 나이별을 가져옵니다..
	 * 
	 * @return 승차권 나이별
	 */
	public  getBookingAge() {
		return this.bookingAge;
	}

	/**
	 * 티켓 가격을 설정합니다..
	 * 
	 * @param bookingPrice
	 *            티켓 가격
	 */
	public void setBookingPrice( bookingPrice) {
		this.bookingPrice = bookingPrice;
	}

	/**
	 * 티켓 가격을 가져옵니다..
	 * 
	 * @return 티켓 가격
	 */
	public  getBookingPrice() {
		return this.bookingPrice;
	}

	/**
	 * 기차역을 설정합니다..
	 * 
	 * @param station
	 *            기차역
	 */
	public void setStation(StationErm station) {
		this.station = station;
	}

	/**
	 * 기차역을 가져옵니다..
	 * 
	 * @return 기차역
	 */
	public StationErm getStation() {
		return this.station;
	}

	/**
	 * 고객 목록을 설정합니다..
	 * 
	 * @param userSet
	 *            고객 목록
	 */
	public void setUserSet(Set<UserErm> userSet) {
		this.userSet = userSet;
	}

	/**
	 * 고객를 추가합니다..
	 * 
	 * @param user
	 *            고객
	 */
	public void addUser(UserErm user) {
		this.userSet.add(user);
	}

	/**
	 * 고객 목록을 가져옵니다..
	 * 
	 * @return 고객 목록
	 */
	public Set<UserErm> getUserSet() {
		return this.userSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookingNm == null) ? 0 : bookingNm.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BookingErm other = (BookingErm) obj;
		if (bookingNm == null) {
			if (other.bookingNm != null) {
				return false;
			}
		} else if (!bookingNm.equals(other.bookingNm)) {
			return false;
		}
		return true;
	}

}
