package korail;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 노선로 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RailErm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 노선 번호. */
	private  railNm;

	/** 기차 도착 시간 . */
	private  trainArrival;

	/** 기차 출발 시간 . */
	private  trainDepart;

	/** 기차 목록. */
	private Set<TrainErm> trainSet;

	/**
	 * 생성자.
	 */
	public RailErm() {
		this.trainSet = new HashSet<TrainErm>();
	}

	/**
	 * 노선 번호을 설정합니다..
	 * 
	 * @param railNm
	 *            노선 번호
	 */
	public void setRailNm( railNm) {
		this.railNm = railNm;
	}

	/**
	 * 노선 번호을 가져옵니다..
	 * 
	 * @return 노선 번호
	 */
	public  getRailNm() {
		return this.railNm;
	}

	/**
	 * 기차 도착 시간 을 설정합니다..
	 * 
	 * @param trainArrival
	 *            기차 도착 시간 
	 */
	public void setTrainArrival( trainArrival) {
		this.trainArrival = trainArrival;
	}

	/**
	 * 기차 도착 시간 을 가져옵니다..
	 * 
	 * @return 기차 도착 시간 
	 */
	public  getTrainArrival() {
		return this.trainArrival;
	}

	/**
	 * 기차 출발 시간 을 설정합니다..
	 * 
	 * @param trainDepart
	 *            기차 출발 시간 
	 */
	public void setTrainDepart( trainDepart) {
		this.trainDepart = trainDepart;
	}

	/**
	 * 기차 출발 시간 을 가져옵니다..
	 * 
	 * @return 기차 출발 시간 
	 */
	public  getTrainDepart() {
		return this.trainDepart;
	}

	/**
	 * 기차 목록을 설정합니다..
	 * 
	 * @param trainSet
	 *            기차 목록
	 */
	public void setTrainSet(Set<TrainErm> trainSet) {
		this.trainSet = trainSet;
	}

	/**
	 * 기차를 추가합니다..
	 * 
	 * @param train
	 *            기차
	 */
	public void addTrain(TrainErm train) {
		this.trainSet.add(train);
	}

	/**
	 * 기차 목록을 가져옵니다..
	 * 
	 * @return 기차 목록
	 */
	public Set<TrainErm> getTrainSet() {
		return this.trainSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((railNm == null) ? 0 : railNm.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RailErm other = (RailErm) obj;
		if (railNm == null) {
			if (other.railNm != null) {
				return false;
			}
		} else if (!railNm.equals(other.railNm)) {
			return false;
		}
		return true;
	}

}
