package korail;

import java.io.Serializable;

/**
 * 좌석 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SeatErm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 좌석 번호. */
	private  seatNm;

	/** 기차. */
	private TrainErm train;

	/** 호차. */
	private  seatTraiin;

	/** 열. */
	private  seatLow;

	/** 좌석 가격. */
	private  seatPrice;

	/**
	 * 생성자.
	 */
	public SeatErm() {
	}

	/**
	 * 좌석 번호을 설정합니다..
	 * 
	 * @param seatNm
	 *            좌석 번호
	 */
	public void setSeatNm( seatNm) {
		this.seatNm = seatNm;
	}

	/**
	 * 좌석 번호을 가져옵니다..
	 * 
	 * @return 좌석 번호
	 */
	public  getSeatNm() {
		return this.seatNm;
	}

	/**
	 * 기차을 설정합니다..
	 * 
	 * @param train
	 *            기차
	 */
	public void setTrain(TrainErm train) {
		this.train = train;
	}

	/**
	 * 기차을 가져옵니다..
	 * 
	 * @return 기차
	 */
	public TrainErm getTrain() {
		return this.train;
	}

	/**
	 * 호차을 설정합니다..
	 * 
	 * @param seatTraiin
	 *            호차
	 */
	public void setSeatTraiin( seatTraiin) {
		this.seatTraiin = seatTraiin;
	}

	/**
	 * 호차을 가져옵니다..
	 * 
	 * @return 호차
	 */
	public  getSeatTraiin() {
		return this.seatTraiin;
	}

	/**
	 * 열을 설정합니다..
	 * 
	 * @param seatLow
	 *            열
	 */
	public void setSeatLow( seatLow) {
		this.seatLow = seatLow;
	}

	/**
	 * 열을 가져옵니다..
	 * 
	 * @return 열
	 */
	public  getSeatLow() {
		return this.seatLow;
	}

	/**
	 * 좌석 가격을 설정합니다..
	 * 
	 * @param seatPrice
	 *            좌석 가격
	 */
	public void setSeatPrice( seatPrice) {
		this.seatPrice = seatPrice;
	}

	/**
	 * 좌석 가격을 가져옵니다..
	 * 
	 * @return 좌석 가격
	 */
	public  getSeatPrice() {
		return this.seatPrice;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seatNm == null) ? 0 : seatNm.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SeatErm other = (SeatErm) obj;
		if (seatNm == null) {
			if (other.seatNm != null) {
				return false;
			}
		} else if (!seatNm.equals(other.seatNm)) {
			return false;
		}
		return true;
	}

}
