package korail;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 기차역 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StationErm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 기차역 번호. */
	private  stationId;

	/** 기차역 명. */
	private  stationNm;

	/** 예매 목록. */
	private Set<BookingErm> bookingSet;

	/**
	 * 생성자.
	 */
	public StationErm() {
		this.bookingSet = new HashSet<BookingErm>();
	}

	/**
	 * 기차역 번호을 설정합니다..
	 * 
	 * @param stationId
	 *            기차역 번호
	 */
	public void setStationId( stationId) {
		this.stationId = stationId;
	}

	/**
	 * 기차역 번호을 가져옵니다..
	 * 
	 * @return 기차역 번호
	 */
	public  getStationId() {
		return this.stationId;
	}

	/**
	 * 기차역 명을 설정합니다..
	 * 
	 * @param stationNm
	 *            기차역 명
	 */
	public void setStationNm( stationNm) {
		this.stationNm = stationNm;
	}

	/**
	 * 기차역 명을 가져옵니다..
	 * 
	 * @return 기차역 명
	 */
	public  getStationNm() {
		return this.stationNm;
	}

	/**
	 * 예매 목록을 설정합니다..
	 * 
	 * @param bookingSet
	 *            예매 목록
	 */
	public void setBookingSet(Set<BookingErm> bookingSet) {
		this.bookingSet = bookingSet;
	}

	/**
	 * 예매를 추가합니다..
	 * 
	 * @param booking
	 *            예매
	 */
	public void addBooking(BookingErm booking) {
		this.bookingSet.add(booking);
	}

	/**
	 * 예매 목록을 가져옵니다..
	 * 
	 * @return 예매 목록
	 */
	public Set<BookingErm> getBookingSet() {
		return this.bookingSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((stationId == null) ? 0 : stationId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		StationErm other = (StationErm) obj;
		if (stationId == null) {
			if (other.stationId != null) {
				return false;
			}
		} else if (!stationId.equals(other.stationId)) {
			return false;
		}
		return true;
	}

}
