package korail;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 기차 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TrainErm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 기차 번호. */
	private  trainId;

	/** 노선로. */
	private RailErm rail;

	/** 기차명. */
	private  trainNm;

	/** 기차 종류. */
	private  trainType;

	/** 기차 상태. */
	private  status;

	/** 예매 목록. */
	private Set<BookingErm> bookingSet;

	/** 좌석 목록. */
	private Set<SeatErm> seatSet;

	/**
	 * 생성자.
	 */
	public TrainErm() {
		this.bookingSet = new HashSet<BookingErm>();
		this.seatSet = new HashSet<SeatErm>();
	}

	/**
	 * 기차 번호을 설정합니다..
	 * 
	 * @param trainId
	 *            기차 번호
	 */
	public void setTrainId( trainId) {
		this.trainId = trainId;
	}

	/**
	 * 기차 번호을 가져옵니다..
	 * 
	 * @return 기차 번호
	 */
	public  getTrainId() {
		return this.trainId;
	}

	/**
	 * 노선로을 설정합니다..
	 * 
	 * @param rail
	 *            노선로
	 */
	public void setRail(RailErm rail) {
		this.rail = rail;
	}

	/**
	 * 노선로을 가져옵니다..
	 * 
	 * @return 노선로
	 */
	public RailErm getRail() {
		return this.rail;
	}

	/**
	 * 기차명을 설정합니다..
	 * 
	 * @param trainNm
	 *            기차명
	 */
	public void setTrainNm( trainNm) {
		this.trainNm = trainNm;
	}

	/**
	 * 기차명을 가져옵니다..
	 * 
	 * @return 기차명
	 */
	public  getTrainNm() {
		return this.trainNm;
	}

	/**
	 * 기차 종류을 설정합니다..
	 * 
	 * @param trainType
	 *            기차 종류
	 */
	public void setTrainType( trainType) {
		this.trainType = trainType;
	}

	/**
	 * 기차 종류을 가져옵니다..
	 * 
	 * @return 기차 종류
	 */
	public  getTrainType() {
		return this.trainType;
	}

	/**
	 * 기차 상태을 설정합니다..
	 * 
	 * @param status
	 *            기차 상태
	 */
	public void setStatus( status) {
		this.status = status;
	}

	/**
	 * 기차 상태을 가져옵니다..
	 * 
	 * @return 기차 상태
	 */
	public  getStatus() {
		return this.status;
	}

	/**
	 * 예매 목록을 설정합니다..
	 * 
	 * @param bookingSet
	 *            예매 목록
	 */
	public void setBookingSet(Set<BookingErm> bookingSet) {
		this.bookingSet = bookingSet;
	}

	/**
	 * 예매를 추가합니다..
	 * 
	 * @param booking
	 *            예매
	 */
	public void addBooking(BookingErm booking) {
		this.bookingSet.add(booking);
	}

	/**
	 * 예매 목록을 가져옵니다..
	 * 
	 * @return 예매 목록
	 */
	public Set<BookingErm> getBookingSet() {
		return this.bookingSet;
	}

	/**
	 * 좌석 목록을 설정합니다..
	 * 
	 * @param seatSet
	 *            좌석 목록
	 */
	public void setSeatSet(Set<SeatErm> seatSet) {
		this.seatSet = seatSet;
	}

	/**
	 * 좌석를 추가합니다..
	 * 
	 * @param seat
	 *            좌석
	 */
	public void addSeat(SeatErm seat) {
		this.seatSet.add(seat);
	}

	/**
	 * 좌석 목록을 가져옵니다..
	 * 
	 * @return 좌석 목록
	 */
	public Set<SeatErm> getSeatSet() {
		return this.seatSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((trainId == null) ? 0 : trainId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TrainErm other = (TrainErm) obj;
		if (trainId == null) {
			if (other.trainId != null) {
				return false;
			}
		} else if (!trainId.equals(other.trainId)) {
			return false;
		}
		return true;
	}

}
